[build]
  # Directory to publish (output of the build command, relative to the base of the project)
  publish = "build"
  
  # Base directory to change to before starting the build
  base = "client/"
  
  # Build command to run
  command = "CI=false npm install && CI=false npm run build"

  # Environment variables specific to the build context
  [build.environment]
    NODE_VERSION = "16.20.2"